#!/usr/bin/env bash

days=("Monday" "Tuesday" "Wednesday" "Thursday" "Friday" "Saturday" "Sunday")

text="The reason that the items are called 'words' is that the shell splits up the input"

for word in $text; do
    echo $word
done