#!/usr/bin/env bash

rand_nums=()

while [ ${#rand_nums[@]} -lt 5 ]; do

    rand_num=$RANDOM

    read -p "Add $rand_num to the list? (y/n) " choice

    if [ "$choice" = "y" ]; then
        rand_nums+=$rand_num
        echo "rand_nums: $rand_nums"
    fi

done

echo "Random Numbers: ${rand_nums[@]}"
