#!/usr/bin/env bash

while true; do

    echo "1) Move Forwards"
    echo "2) Move Backwards"
    echo "3) Turn Left"
    echo "4) Turn Right"
    echo "5) Explore"
    echo "0) Quit"

    read -p "What will you do: " choice

    if [ $choice -eq 0 ]; then
        exit
    fi

    clear

done
