#!/usr/bin/env bash


tput setaf 33

read -p "Show doc of: " doc

prefix=$(echo $doc | cut -c -1)
docName=$(echo $doc | cut -c 2-)

if [ "$prefix" == ";" ]; then
  if [ -e /tmp/go-docs/${docName}.go ]; then
    lvim /tmp/go-docs/${docName}.go
  else
    go doc -all $docName > /tmp/go-docs/${docName}.go
    lvim /tmp/go-docs/${docName}.go
  fi
else
  man $doc
fi

